# Generated by Django 4.1.1 on 2022-10-31 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('password', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('detail_id', models.IntegerField(blank=True, null=True)),
                ('chatbot_title', models.CharField(blank=True, max_length=250)),
                ('node_position', models.TextField(blank=True, null=True)),
                ('btn_name', models.CharField(blank=True, max_length=250)),
                ('btn_position', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gambit_container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambit_id', models.IntegerField(blank=True, null=True)),
                ('gambit_name', models.CharField(blank=True, max_length=250)),
                ('chatbot_name', models.CharField(blank=True, max_length=250)),
                ('gambit_position', models.TextField(blank=True, null=True)),
                ('line_position', models.TextField(blank=True, null=True)),
                ('btn_id', models.CharField(blank=True, max_length=250)),
                ('conn_btn_name', models.TextField(blank=True, null=True)),
                ('line_conn_position', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_json', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='New_Gambit_container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Gambit_created_id', models.IntegerField(blank=True, null=True)),
                ('New_Gambit_created_name', models.CharField(blank=True, max_length=250)),
                ('chatbot_name', models.CharField(blank=True, max_length=250)),
                ('connec_btn_value', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Scratch_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_title', models.CharField(blank=True, max_length=250)),
                ('scratch_id', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=250)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('chatbot_title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chatbot.scratch_values')),
            ],
        ),
        migrations.CreateModel(
            name='New_chatbot_values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbot_id', models.IntegerField(blank=True, null=True)),
                ('chatbot_title', models.ForeignKey(db_column='chatbot_title', on_delete=django.db.models.deletion.CASCADE, to='chatbot.scratch_values')),
                ('name', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='chatbot.detailform')),
            ],
        ),
    ]
