# Generated by Django 4.1.1 on 2022-10-31 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewJoin_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.text')),
            ],
        ),
        migrations.RemoveField(
            model_name='detailform',
            name='btn_name',
        ),
        migrations.RemoveField(
            model_name='detailform',
            name='btn_position',
        ),
        migrations.RemoveField(
            model_name='detailform',
            name='node_position',
        ),
        migrations.RemoveField(
            model_name='gambit_container',
            name='btn_id',
        ),
        migrations.RemoveField(
            model_name='gambit_container',
            name='conn_btn_name',
        ),
        migrations.RemoveField(
            model_name='gambit_container',
            name='gambit_position',
        ),
        migrations.RemoveField(
            model_name='gambit_container',
            name='line_conn_position',
        ),
        migrations.RemoveField(
            model_name='gambit_container',
            name='line_position',
        ),
        migrations.RemoveField(
            model_name='scratch_values',
            name='image',
        ),
        migrations.AddField(
            model_name='detailform',
            name='x_coordinate_of_button',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detailform',
            name='y_coordinate_of_button',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gambit_container',
            name='gambit_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
        migrations.AddField(
            model_name='newjoin_detail',
            name='name_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.detailform'),
        ),
    ]
